apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: bitbucket-binding-pr
spec:
  params:
    - name: gitrevision
      value: $(body.pullrequest.destination.branch.name)
    - name: gitrepositoryurl
      value: $(body.repository.links.html.href)
    - name: image-version
      value: $(extensions.truncate)